[workspace]
members = ["crates/assistant-core", "crates/assistant-cli"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Assistant Contributors"]
license = "MIT OR Apache-2.0"
